version: '3.7'
services:
  dj:
#    build: ./simple_solutions_stripe
    image: phdmabuze/django_stripe_dj:latest
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - static_volume:/simple_solutions_stripe/static
    command: gunicorn simple_solutions_stripe.wsgi --bind 0.0.0.0:8000
    entrypoint: /entrypoint.sh
    restart: unless-stopped
  db:
    image: postgres:14.10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/simple_solutions_stripe/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - dj
    restart: unless-stopped
volumes:
  postgres_data:
  static_volume: