# Generated by Django 4.2.7 on 2023-12-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'rub'), ('usd', 'usd'), ('eur', 'eur'), ('cny', 'cny')], default='rub', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.CharField(max_length=128),
        ),
    ]
